export const keyData = [
  {
    name: "esc",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    type: "action",
  },
  {
    type: "action",
    name: "F1",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "F2",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    type: "action",
    className: "symbol",
  },
  {
    name: "F3",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "F4",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "F5",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "F6",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "F7",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "F8",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "F9",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "F10",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "F11",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "F12",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "Prt",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "Ins",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "`",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol ctrl",
    name2:'~',
  },
  {
    name: "1",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'!',
  },
  {
    name: "2",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'@',
  },
  {
    name: "3",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'#',
  },
  {
    name: "4",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'$',
  },
  {
    name: "5",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'%',
  },
  {
    name: "6",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'^',
  },
  {
    name: "7",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'&',
  },
  {
    name: "8",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'*',
  },
  {
    name: "9",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'(',
  },
  {
    name: "0",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:')',
  },
  {
    name: "-",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'_',
  },
  {
    name: "=",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'+',
  },
  {
    name: "Backspace",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    type: "backspace",
    className: "delete lastitem",
  },
  {
    name: "tab",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "tab",
    type: "tab",
  },
  {
    name: "q",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "w",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "e",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "r",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "t",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "y",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "u",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "i",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "o",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "p",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "[",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'{',
  },
  {
    name: "]",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'}',
  },
  {
    name: "\\",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol lastitem",
    name2:'|',
  },
  {
    name: "Caps Lock",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "capslock",
    type: "capslock",
  },
  {
    name: "a",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "s",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "d",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "f",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "g",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "h",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "j",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "k",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "l",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: ";",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:':',
  },
  {
    name: "'",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'"',
  },
  {
    name: "Enter",
    type: "enter",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "return lastitem",
  },
  {
    name: "shift",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    type: "shift",
    className: "left-shift",
  },
  {
    name: "z",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "x",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "c",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "v",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "b",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "n",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: "m",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "letter",
  },
  {
    name: ",",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'<',
  },
  {
    name: ".",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'>',
  },
  {
    name: "/",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    name2:'?',
  },
  {
    name: "Shift",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "right-shift lastitem",
    type: "shift",
  },
  {
    name: "ctrl",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "ctrl",
    type: "action"
  },
  {
    name: "Fn",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    type: "action"
  },
  {
    name: "Win",
    type: "action",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "Alt",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    className: "symbol",
    type: "action",
  },
  {
    name: "space",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    type: "space",
    className: "space lastitem",
  },
  {
    name: "Alt",
    keyAddress: "left",
    onDown: false,
    pressed: false,
    type: "action",
    className: "symbol",
  },
  {
    name: "ctrl",
    keyAddress: "left",
    onDown: false,
    type: "action",
    pressed: false,
    className: "action",
  },
  {
    name: "PgUp",
    type: "action",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "PgDn",
    type: "action",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "Home",
    type: "action",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "End",
    type: "action",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "Num",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "num",
    type: "numlock",
  },
  {
    name: "/",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "*",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "-",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "7",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "ctrl",
  },
  {
    name: "8",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "9",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "+",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol height",
  },
  {
    name: "4",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "ctrl mt45",
  },
  {
    name: "5",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol mt45",
  },
  {
    name: "6",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol mt45",
  },
  {
    name: "1",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "ctrl",
  },
  {
    name: "2",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "3",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol",
  },
  {
    name: "Enter",
    type: "enter",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol height",
  },
  {
    name: "0",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "ctrl mt45 wid",
  },
  {
    name: ".",
    keyAddress: "right",
    onDown: false,
    pressed: false,
    className: "symbol mt45",
  },
];
